### ISSUE TITLE
Feature Request: Allow non OBS audio sources.

### ISSUE THREAD

**Issue by Voidion** [univrsal/spectralizer#10]
Please add support for non OBS audio sources, so support for Spotify, Pretzel.rocks, game sources etc.

It's very difficult to use just Desktop Audio when you have more than just music active

**Comment by univrsal** [comment]
That's not possible the way audio on windows works. If it were that easy OBS Studio would offer a way to capture audio for individual processes, but it can't because it's handled by the operating system.
You can only achieve this by using something like [Voice Meeter](https://www.vb-audio.com/Voicemeeter/index.htm) or maybe a physical mixer could work as well.
The only other way I know is using Linux and JACK which allows for customizable audio routing, but I doubt that that is a feasible option.
