### ISSUE TITLE
spectralizer.so cannot be open  because developer cannot be verified..

### ISSUE THREAD

**Issue by gateway** [univrsal/spectralizer#17]
Just tried this on my mac running 10.15.3

![image](https://user-images.githubusercontent.com/519563/78517867-74a2eb80-7773-11ea-9fdd-e83367754c2e.png)

any thoughts?

**Comment by univrsal** [comment]
Does that happen when you run obs studio?

**Comment by gateway** [comment]
Yep.. as soon as I run, this pops up.. i hit cancel but it doesn't load the plugin

**Comment by univrsal** [comment]
Well that's problematic. I have absolutely no experience with macOS outside porting the plugin to it so I'm not going to be of much help here. I only know that this warning can be disabled for apps by following these instructions: https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac
But I don't know if they work for something like the plugin since it's not a real application

**Comment by nittanygeek** [comment]
Go to System Preferences > Security and Privacy, and under the General Tab, you should see a button to "Allow Anyways" for the spectralizer verification.

**Comment by x-stefan** [comment]
You can remove the quarantine with `sudo xattr -d com.apple.quarantine pathtoplugin/bin/spectralizer.so` as well.

**Comment by voxxit** [comment]
@x-stefan Yeah, I will make a pull request with that change to the `install-mac.sh` script. Assuming the maintainers can't sign their code correctly...

edit: DONE! :)

**Comment by univrsal** [comment]
>Assuming the maintainers can't sign their code correctly...

It's not about whether I can, it's about whether I want to fork out 100 dollars a year to a company I don't like, regardless I appreciate the contribution.
