### ISSUE TITLE
Color Correction filter doesn't work if it's the first in the list

### ISSUE THREAD

**Issue by WizardCM** [univrsal/spectralizer#2]
Reproduction steps:

1. Add an Audio Visualiser source to your scene
2. Select an audio device so that the visualiser starts moving, then hit OK
3. Right click the source and select Filters
4. Click + then select "Color Correction"
5. Adjust the opacity to 50%. **Notice the opacity of the visualiser doesn't change**
6. Add another filter, like Scroll. Place it above the Color Correction filter. This will cause the opacity to go into effect.

OBS Studio v24.0.3 on Windows 10 64bit, using the tagged v1.0.

**Comment by univrsal** [comment]
Edit: Nevermind, I never knew that I have to add ``OBS_SOURCE_CUSTOM_DRAW`` to the output flags of the source. That's why I always had issues with filters.

~Is there a chance that this might be an obs bug? I copied the code 1:1 from color source and the filter still doesn't work:~
![image](https://user-images.githubusercontent.com/8353672/67107949-b512ab00-f1cd-11e9-80b1-00f36997ea03.png)
![image](https://user-images.githubusercontent.com/8353672/67107700-3c135380-f1cd-11e9-9738-088027df9a6c.png)

**Comment by univrsal** [comment]
Also I saw you mentioned that the program lacked logging, I put most logging into the debug log because I didn't want to spam the logs. Which parts do you think could use logging?

**Comment by WizardCM** [comment]
Mostly whether it successfully captured an audio device, or if the audio device has been lost.

**Comment by univrsal** [comment]
I added logging to the audio source capturing
