### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by R3clu23** [univrsal/spectralizer#20]
I download the necessary files and copied them to the "obs-plugin" directory and loaded up OBS, but I don't see it for a new source.

Is there a step-by-step installation guide?  I looked on the OBS Forum page, but the installation was very vague
![obs-plugin](https://user-images.githubusercontent.com/23437687/80165483-91c81e80-85a9-11ea-98bf-7d18cf18eaeb.jpg)
.

**Comment by univrsal** [comment]
You downloaded the source code instead of the actual plugin, also you extracted it to the wrong folder.
Click on Download on the obs forums and download the spectralizer.v1.2.win32.64.zip file, then follow the instructions

1. Open your obs-studio installation folder (eg. Right click on the shortcut and click "Open file location")
2. Navigate two directories up
3. Drop the contents of the folder "plugin" from the zip archive in the directory you just opened
4. Merge the files
5. Spectralizer should now show up as a source option in obs-studio

**Comment by R3clu23** [comment]
Thank You! Closed.
