### ISSUE TITLE
Can allow color dynamics？

### ISSUE THREAD

**Issue by yigexuezha** [univrsal/spectralizer#31]
Can allow color dynamics？

**Comment by univrsal** [comment]
can you be a bit more specific?

**Comment by yigexuezha** [comment]
1. The bar color, make it dynamics. Like a rainbow. And can set change color every xx seconds.
2. Increase the density of the bar. When detail is high( bar weight and bar spacing is low), a lot of bar don't wave. Especially when light music is played.

Hope you can add some features.Thank you！

**Comment by univrsal** [comment]
The first one you can do via masks and shaders, which is why I won't add it myself. The second one I don't really get, when you play quiet music the visualizer doesn't move, because it's quiet that's just how it's supposed to work. If you want it to be really sensitive you can turn off automatic scaling but that's about it. I am redoing the spectrum code to fix #3 but nothing else is planned in that regard.
